language: ruby
sudo: false
cache: bundler
script:
- bundle exec rake spec
rvm:
- 1.9.3
- 2.0.0
- 2.1.9
- 2.4.1
matrix:
  fast_finish: true
deploy:
  provider: rubygems
  api_key:
    secure: "WtAaU2/QJdYpiD9wWGtq9FkkMzJc+8Std+yIQXi8I+uexAVvCXSz2osjdlgzRKW1c09LyEVwR+COxqvOy55sDZUWQq4eynPU3zB+Lcr8xg7VsfdSkjq4oAhXt4FnG65ZvOpOQNpv3sULGhIteAF9Fb4TWKAA8dT5rJfN1PmJ8fw="
  on:
    rvm: 2.1.5
    tags: true
    all_branches: true
notifications:
  email: false
